name: zep-ce

services:
  zep:
    image: zepai/zep:latest
    #    build:
    #      context: .
    #      dockerfile: Dockerfile.ce
    ports:
      - "8021:8000"
    volumes:
      - ./zep.yaml:/app/zep.yaml
    environment:
      - ZEP_CONFIG_FILE=zep.yaml
    networks:
      - zep-network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: ankane/pgvector:v0.5.1
    container_name: zep-ce-postgres
    restart: on-failure
    shm_size: "128mb" # Increase this if vacuuming fails with a "no space left on device" error
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - zep-network
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - zep-db:/var/lib/postgresql/data
    ports:
      - "5421:5432"
  neo4j:
    image: neo4j:5.22.0
    networks:
      - zep-network
    healthcheck:
      test: wget http://localhost:7687 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    ports:
      - "7421:7474" # HTTP
      - "7621:7687" # Bolt
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/zepzepzep
volumes:
  neo4j_data:
  zep-db:
networks:
  zep-network:
    driver: bridge
